### PR TITLE
Fix non-loading page on iOS 10

### PR DESCRIPTION
**Pull request by glangmead**
Move jquery libraries to be included first.
Work around https://github.com/webcomponents/webcomponentsjs/issues/617 by trying webcomponents-lite.
With these changes, after "make", I can load the site on Safari for Mac (macOS 10.12.1) as well as Safari on iPad, iOS 10.

### CODE REVIEW

**Comment by gebner** [comment]
With the lite version I get an error [here](https://github.com/leanprover/tutorial/blob/master/juicy-ace-editor.html#L39) because `Platform.ShadowCSS` is not defined.  Then the code snippets in the text are not visible (using chromium here).

Can you see these code snippets in safari?

2016-11-22-171042_1920x1080_scrot

**Comment by glangmead** [comment]
I see them, but only the first one in a chapter is styled correctly. The others lack styling and line breaks, which is not good. Guess it'll need the real fix to webcomponents?

**Comment by gebner** [comment]
Have you tried the latest 0.7.23 release?  As far as I can tell from the git log, it should include the fix for this issue.

**Comment by glangmead** [comment]
Aha! Thanks, the thread for issue 617 over at webcomponents did not make that obvious. By rolling back the -lite change and updating to 0.7.23 things look good and the styling of the code samples is back.

**Comment by gebner** [comment]
Awesome!  Could you squash all four commits into one and change the commit message according to the convention here, i.e. something like `fix(index.html,header/html.org): support safari`?  I'll merge it then.  Thank you.

**Comment by glangmead** [comment]
I opened a new cleaner PR with one commit over here: https://github.com/leanprover/tutorial/pull/205. Closing this one.

**Pull request closed without merging**
