### PR TITLE
polishing and updates

### PR DESCRIPTION
**Pull request by avigad**
Whew, I cleared a lot of things off my to-do list. Leo, please take a look at the discussion of universe levels at the end of Chapter 6.

Still on my to-do list:

Ed's corrections
Style guidelines
Work on the tactic chapter
Write the classical axioms chapter
Write the homotopy type theory chapter

### CODE REVIEW

**Comment by avigad** [comment]
Is there something I should do to fix this? "make test" succeeds for me.

**Comment by leodemoura** [comment]
I’m working from home today.
Tomorrow, I will update the Ubuntu PPA from my office

Best,
Leo

**Comment by avigad** [comment]
O.k., there is no rush. I just wanted to make sure I didn't miss something. Thanks.

**Comment by soonhokong** [comment]
Dear @avigad, FYI, now travis-ci is using 20150305 version (https://github.com/leanprover/lean/commit/e4060a5614fea07029de504c11cc5d5319352e03). There is a failure at chatper 8 of the tutorial, starting from line 607:

```lean
example (p q r : Prop) : p ∧ (q ∨ r) ↔ (p ∧ q) ∨ (p ∧ r) :=
iff.intro
  (assume H : p ∧ (q ∨ r),
    have Hp : p, from and.elim_left H,
    show (p ∧ q) ∨ (p ∧ r), from
    proof
      or.elim (and.elim_right H)
        (assume Hq : q,
          show (p ∧ q) ∨ (p ∧ r), from or.inl (and.intro Hp Hq))
        (assume Hr : r,
          show (p ∧ q) ∨ (p ∧ r), from or.inr (and.intro Hp Hr))
    qed)
  (assume H : (p ∧ q) ∨ (p ∧ r),
    show p ∧ (q ∨ r), from
    proof
      or.elim H
        (assume Hpq : p ∧ q,
          have Hp : p, from and.elim_left Hpq,
          have Hq : q, from and.elim_right Hpq,
          show p ∧ (q ∨ r), from and.intro Hp (or.inl Hq))
        (assume Hpr : p ∧ r,
          have Hp : p, from and.elim_left Hpr,
          have Hr : r, from and.elim_right Hpr,
          show p ∧ (q ∨ r), from and.intro Hp (or.inr Hr))
    qed)
```

We have an error message: `unknown identifier 'Hp'` at line 9.

**Comment by leodemoura** [comment]
Today, I changed how `proof ... qed` blocks are compiled.  
This is a side-effect of the change.
I will fix the tutorial tomorrow.

**Comment by avigad** [comment]
I am confused... It looks like this pull request was never merged. Is there something I should do?

**Comment by soonhokong** [comment]
Merged via 6eb287c15709e9a1daef032c72f3c59711590f53

**Comment by soonhokong** [comment]
@leodemoura, I've checked that all the tests in the tutorial are passed by the latest version of lean.

**Comment by avigad** [comment]
Thanks!

**Pull request closed without merging**
