### PR TITLE
more routine polishing

### PR DESCRIPTION
**Pull request by avigad**
I made it through chapter 10.

### CODE REVIEW

**Comment by soonhokong** [comment]
Dear @avigad, there is a test failure in Chapter 7, could you check https://travis-ci.org/leanprover/tutorial/jobs/67145954#L7337-L7339 ? I guess it's not because of your changes but because of some recent changes in Lean?

```
-- testing 07_Induction_and_Recursion.org
code fragment #1 worked
code fragment #2 worked
code fragment #3 worked
code fragment #4 worked
code fragment #5 worked
code fragment #6 worked
code fragment #7 worked
code fragment #8 worked
code fragment #9 worked
code fragment #10 worked
ERROR executing 07_Induction_and_Recursion.org.11.lean, for in_code_block block starting at 305, produced output:
07_Induction_and_Recursion.org.11.lean:12:22: error: unknown identifier 'succ_inj'
```

**Comment by avigad** [comment]
I just fixed this, and also updated the tutorial to reflect a change that Leo just made to the handling of type classes.

**Comment by soonhokong** [comment]
@avigad, thank you! I'll monitor travis and merge this one if there is no error on Travis.

**Comment by avigad** [comment]
This completes a full pass through the tutorial. I think it is in good shape. My plan now is to add three chapters and an appendix:

- Chapter 13, Equality and Dependent Types: equality of dependent functions, casts, heterogeneous equality, equality of records and structures (some of this material will be moved from Chapter 6, Inductive Types)

- Chapter 14, More Tactics: congruence, exfalso, contradiction, refine, trace, induction, change, assert_hypothesis (what does this do?), the "let" construction, constructor, fconstructor, existsi, split, left, right, injection, subst, subsvars, reflexivity, symmetry, transitivity, combinators

- Chapter 15, Homotopy Type Theory: I have lecture notes for this. It will be a high-level overview; the examples will not run in the online version

- Appendix: Quick Reference

I will work on the quick reference first.

Comments and suggestions are welcome. @soonhokong, there is no rush, but please don't forget to pull this within the next few days.

**Comment by soonhokong** [comment]
merged.

**Pull request closed without merging**
