### PR TITLE
fix(02,05,08,11): unresolved inter-file links

### PR DESCRIPTION
**Pull request by soonhokong**
@avigad, I found that there are some broken inter-file links. Could you review my changes?

### CODE REVIEW

**Comment by soonhokong** [comment]
@avigad, I'm still fixing up some LaTeX errors, please wait until I finish the fix.

**Comment by soonhokong** [comment]
@avigad, OK. Now it's ready for a review.

**Comment by avigad** [comment]
I am sorry I did such a bad job with the links! I just reviewed the changes, and they look good.

**Comment by soonhokong** [comment]
Closed by https://github.com/leanprover/tutorial/commit/eff56214e61b87ec9177106d3afb37876079265e.

@avigad, I'm happy to fix small issues. Here are some lessons that I re-learned by this fix:

 1. Inter-file link has `[[file:08_Building_Theories_and_Proofs.org::#Elaboration_and_Unification][Elaboration and Unification]]` format.
 2. The last part (i.e. `[Elaboration and Unification]`) should not include `_`. LaTeX will complain about it if there is one.

**Comment by avigad** [comment]
Thanks. I have almost internalized the method for links, but I still make mistakes sometimes.

The next time I make a pass through the tutorial, I will add references for the index. I haven't forgotten that.

**Pull request closed without merging**
