### PR TITLE
Typos in tutorial

### PR DESCRIPTION
**Pull request by tomsib2001**
Minor typos corrected. PR to be updated if others found.

### CODE REVIEW

**Comment by tomsib2001** [comment]
There seems to be a bug in the checks as the reported error mentions the version of cmake.

**Comment by soonhokong** [comment]
> There seems to be a bug in the checks as the reported error mentions the version of cmake.

@tomsib2001, that's right. I'll fix that soon.

**Comment by soonhokong** [comment]
@tomsib2001, the problem in Travis-CI is fixed now.

**Comment by soonhokong** [comment]
@avigad, if you think https://github.com/leanprover/tutorial/pull/200/commits/7ea45282724e3a8e9c922bbbfe92c84c1115520a is good to be merged, please let us know.

**Comment by avigad** [comment]
Yes, please do! @tomsib2001, many thanks.

**Comment by soonhokong** [comment]
merged by 0a2d14e

**Pull request closed without merging**
