### PR TITLE
fix(02,06,07): suggested by LiamGoodacre

### LINKED ISSUE #73: found a few issues
2.3 Function Abstraction and Evaluation
---

> Conversely, if we have `p : nat × nat`, then we have `pr1 p : nat` and `pr2 : nat`.

The last bit:

> `pr2 : nat`

Should be

> `pr2 p : nat`

2.5 Local definitions [0]
---

> The expression `let a := t1 in t2` is definitionally equal to the result of replacing every occurrence of `a` in `t1` by `t2`.

The last bit:

> `a` in `t1` by `t2`

Should be

> `a` in `t2` by `t1`

2.5 Local definitions [1]
---

> Notice that the meaning of the expression `let a := t1 in t2` is very similar to the meaning of `(λa, t1) t2`, but the two are not the same. In the first expression, you should think of every instance of `a` in `t2` as a syntactic abbreviation for `t1`. In the second expression, `a` is a variable, and the expression `λa, t1` has to make sense independent of the value of `a`. The `let` construct is a stronger means of abbreviation, and there are expressions of the form `let a := t1 in t2` that cannot be expressed as `(λa, t1) t2.`

Shouldn't all the occurrences of `(λa, t1) t2` actually be `(λa, t2) t1` - as we are saying that `a` should represent an abbreviation for `t1` within `t2`.  Which is how `let a := t1 in t2` reads.

6.2 Constructors with Arguments
---

Describes example definitions for `pr1` and `pr2`:

~~~lean
definition pr1 {A B : Type} (p : A × B) : A :=
prod.rec_on p (λa b, a)

definition pr2 {A B : Type} (p : A × B) : A :=
prod.rec_on p (λa b, a)
~~~

The definition for `pr2` is just a copy of `pr1`.  I believe the example is supposed to be:

~~~lean
definition pr1 {A B : Type} (p : A × B) : A :=
prod.rec_on p (λa b, a)

definition pr2 {A B : Type} (p : A × B) : B :=
prod.rec_on p (λa b, b)
~~~

6.4 Defining the Natural Numbers
---

> Consider, for example, the addition function `add m n` on the natural numbers. Fixing `m`, we can define addition by recursion on `n`. In the base case, we set `add m zero` to `n`. In the successor step, assuming the value `add m n` is already determined, we define `add m (succ n)` to be `succ (add m n)`.

Where it says:

> set `add m zero` to `n`

Should be:

> set `add m zero` to `m`

7.5 Inaccessible Terms
---

> In the following example can be find in [1].

I think this is supposed to say something like:

> The following example can be found in [1].

### PR DESCRIPTION
**Pull request by soonhokong**
attempt to fix #73

@avigad and @LiamGoodacre: Could you review the changes?

### CODE REVIEW

**Comment by avigad** [comment]
Yes, those are helpful fixes. There is still one typo in 07: "can be find" should be "can be found". If you don't fix it now, though, I'll fix it during the week. I have a round of corrections to make to 08 and 09.

**Comment by LiamGoodacre** [comment]
06 now wouldn't type check;

Previously:

```lean
definition pr2 {A B : Type} (p : A × B) : A :=
prod.rec_on p (λa b, a)
```

The `a` was changed to `b` without updating the result type:

```lean
definition pr2 {A B : Type} (p : A × B) : A :=
prod.rec_on p (λa b, b)
```

The result type should be `B`, as in:

```lean
definition pr2 {A B : Type} (p : A × B) : B :=
prod.rec_on p (λa b, b)
```

**Comment by soonhokong** [comment]
Right.. I'll fix it soon.

**Comment by soonhokong** [comment]
@LiamGoodacre, thanks for finding those issues. I've only fixed up to chapter 6. 
@avigad, I didn't change chapter 7 and 8 to prevent merge conflicts.

**Comment by avigad** [comment]
I won't be able to work on the tutorial again until Tuesday afternoon or Wednesday.

Are there proposed changes to 7 and 8? If so, please feel free to make them.

**Comment by soonhokong** [comment]
I will do that this morning.

**Comment by soonhokong** [comment]
@avigad, it's done by 1b0ae9b92b6a68b499724ed09fb48f431a486117 andb53b26bf92a36a1d6174dfa9f7b27b1610836eea.

**Comment by LiamGoodacre** [comment]
@soonhokong you're welcome.  I enjoyed the tutorial, I went through the whole thing in an afternoon :)

**Comment by avigad** [comment]
@LiamGoodacre

Thanks, Liam, this is really encouraging. There is a long way to go, and we really appreciate your willingness to experiment with Lean at this early stage.

**Pull request merged**
