### PR TITLE
Fix cask execution

### PR DESCRIPTION
**Pull request by Kha**
`make` died on trying to open `~/.cask/cask.el` for me. I _think_ this should be the way to make cask execute purely locally.

### CODE REVIEW

**Comment by soonhokong** [comment]
Thanks for the checking. I think there is a small issue here.

The following is line 53-55 of [Makefile](https://github.com/leanprover/tutorial/blob/master/Makefile#L53-L55):
```makefile
.cask: Cask
	@EMACS=$(EMACS_BIN) $(CASK_BIN) install
	@touch .cask
```

Previously, line 54 is expanded into "EMACS=emacs cask install" and `cask install` is executed with an environment where `EMACS=emacs`. With the current PR, line 54 is expanded into "EMACS=cask exec emacs cask install". It run emacs openning `cask` and `install` files.

It seems that we need to quote `EMACS=$(EMACS_BIN)` but I couldn't figure out a way now. Do you have any idea?

**Comment by Kha** [comment]
Oops, I should have checked all uses of EMACS_BIN. I've inserted `exec` locally instead now.

**Comment by soonhokong** [comment]
@Kha, thanks! This works.

I'll merge your PRs once we resolve #196.

**Comment by soonhokong** [comment]
Merged by 48cb5dbf2f88ca7aa7d43102dd8a7c964f7da05c.

**Pull request closed without merging**
