### PR TITLE
write type classes chapter, move tactic section

### PR DESCRIPTION
**Pull request by avigad**
Feel free to add / correct information on type classes. At the end of the section, I wanted to tell users how to modify the "prolog program" by setting priorities of instances, but I could no longer find an instance in the library. Is it still possible to do that?

### CODE REVIEW

**Comment by leodemoura** [comment]
BTW, I had to cite type classes in Chapter 09.
I will also have to talk about type classes in other tactics (e.g., apply). 
Should we switch 09 and 10?

**Comment by avigad** [comment]
Sure. The order of 9, 10, 11 is largely arbitrary. 8 talks about the
elaborator, and Type Classes are natural to put after that.

Should we do

  Type Classes
  Structures (since they use type classes)
  Tactics (since they are largely independent)

?

**Comment by leodemoura** [comment]
I agree.


Thanks,

Leo


________________________________

**Comment by avigad** [comment]
I am heading out now, but I will merge your changes and do the renaming first thing tomorrow morning.

**Comment by avigad** [comment]
I had a bit of trouble with git, but hopefully everything is o.k. now. I have reordered the chapters as we discussed. @leodemoura, let me know if I should add something about setting priorities of instances (and, if so, how to do it).

**Comment by avigad** [comment]
@leodemoura, @soonhokong This pull request is waiting to be merged. It has a new chapter on type classes.

**Pull request closed without merging**
