### PR TITLE
feat(12_Axioms.org): add chapter on axioms

### PR DESCRIPTION
**Pull request by avigad**
It could use some more work, but it will be sufficient reading for the lecture on additional axioms. Chapter 13 will be Homotopy Type Theory, which will complete the core part of the tutorial.

@leodemoura, I added a "philosophical" discussion of constructive vs. classical mathematics. Let me know if it is not o.k. with you.

@soonhokong, I am getting red boxes around some of the symbols in chapter 12, including emptyset, set intersection, and [[ - ]]. At least the first two of these are in unixode.sty. Is there something more I need to do to make the symbols work?

### CODE REVIEW

**Comment by soonhokong** [comment]
>  I am getting red boxes around some of the symbols in chapter 12, including emptyset, set intersection, and [[ - ]]. At least the first two of these are in unixode.sty. Is there something more I need to do to make the symbols work?

@avigad, you need to add the symbols to pygments. I'll do it tonight and write another comment here when it's done.

**Comment by avigad** [comment]
Thanks. If you tell me how to do it, I can do it in the future.

I just noticed issue #84 and responded to it, and added it to the pull request.

**Comment by soonhokong** [comment]
Dear @avigad, could you check the chapter 8? I have a failed testcase while running `make test`.

```lean
import standard
import data.int
open int eq.ops

context mod_m
parameter (m : ℤ)
variables (a b c : ℤ)

definition mod_equiv := (m | b - a)

notation a `≡`:50 b := mod_equiv a b

theorem mod_refl : a ≡ a := !sub_self⁻¹ ▸ !dvd_zero

theorem mod_sym (H : a ≡ b) : b ≡ a :=
have H1 : (m | -(b - a)), from iff.mp' !dvd_neg_iff_dvd H,
int.neg_sub b a ▸ H1

theorem mod_trans (H1 : a ≡ b) (H2 : b ≡ c) : a ≡ c :=
have H1 : (m | (c - b) + (b - a)), from !dvd_add H2 H1,
eq.subst
(calc
(c - b) + (b - a) = c - b + b - a  : add.assoc
... = c + -b + b - a : rfl
... = c - a          : neg_add_cancel_right)
H1
end mod_m

check mod_refl
check mod_sym
check mod_trans
```

```text
08_Building_Theories_and_Proofs.org.22.lean: error: 08_Building_Theories_and_Proofs.org.22.lean:15:32: error: unexpected token
ERROR executing 08_Building_Theories_and_Proofs.org.22.lean, for in_code_block block starting at 902, produced output:
08_Building_Theories_and_Proofs.org.22.lean:9:27: error: invalid expression starting at 9:24
08_Building_Theories_and_Proofs.org.22.lean:11:23: error: unknown identifier 'mod_equiv'
08_Building_Theories_and_Proofs.org.22.lean:13:21: error: unexpected token
08_Building_Theories_and_Proofs.org.22.lean:15:23: error: unexpected token
```

**Comment by avigad** [comment]
The problem in chapter 8 was easy to fix: Leo changed the "divides" symbol from | to \|.

There were some problems in chapter 11 also. One was that Leo changed some square brackets to round brackets. But there was another problem, a tactic proof with "match" that works fine when only data.nat is loaded, but fails when the standard library is loaded. I don't know why, but I replaced with with a proof that works. So now the tutorial should check o.k.

@leodemoura, the proof that doesn't work is this:
``` lean
import standard
import data.nat
open nat

example (x : ℕ) (H : x ≠ 0) : succ (pred x) = x :=
begin
  revert H,
  match x with
  | 0      := by intro H1; exact (absurd rfl H1)
  | succ y := by intro H1; apply rfl
  end
end
```

If you delete ```import standard```, it works. As it is, the error message says "deep recursion was detected at 'instantiate metavars'"

**Comment by soonhokong** [comment]
> Thanks. If you tell me how to do it, I can do it in the future.

@avigad, I added ∈, ∅, ∩, ∪, ⟦, ⟧ to pygments:

https://bitbucket.org/leanprover/pygments-main/commits/d3886d317dcf422e8d92c3507a6359fbbc32345f

**Comment by soonhokong** [comment]
Merged by 13101c3959393ce3373b42b83823b18a0af4bbbd.

**Comment by leodemoura** [comment]
Regarding the proof that doesn't work anymore. The problem is the new coercion `map.func` defined in `set`. The problem is that if the source type is not know at preprocessing time, then it will be considered, and really nasty elaboration problems are generated. It will always be considered because the target function type is essentially any function.

**Comment by avigad** [comment]
Ouch, that is depressing. I am sorry to cause so much trouble. 

At least, we can move the coercion to the namespace "map", so that it won't be present unless the user opens the namespace. I will think about whether there is a better solution.

**Pull request closed without merging**
