### PR TITLE
Various corrections in chapters 5 and 6 of online tutorial

### PR DESCRIPTION
**Pull request by Zimmi48**
Hi. Most of these corrections are typos but there are also one or two suggestions to make the text clearer.

### CODE REVIEW

**Comment by avigad** [comment]
Thanks!

**Comment by soonhokong** [comment]
- @Zimmi48, thanks for the corrections and suggestions. 
 - @avigad, do you think they are all good to be merged? I'll do the merge if it's the case.

**Comment by avigad** [comment]
@soonhokong Yes, they are very helpful!

**Comment by soonhokong** [comment]
@Zimmi48 and @avigad, merged by 0860b46!

**Pull request closed without merging**
